export function createLoggerOptions(config) {
  return {
    level: config.LOG_LEVEL,
    redact: {
      censor: "[REDACTED]",
      paths: [
        "req.headers.authorization",
        "req.headers.cookie",
        "req.body.password",
        "req.body.passwordConfirmation",
        "req.body.token",
        "req.body.refreshToken",
        "req.body.notes",
        "req.body.message",
        "req.body.address",
        "req.body.emergencyContact",
        "req.body.emergencyContact.*",
        "res.headers.set-cookie",
        "password",
        "passwordHash",
        "token",
        "refreshToken",
        "*.password",
        "*.passwordHash",
        "*.token",
        "*.refreshToken",
        "*.notes",
        "*.address",
        "*.emergencyContact",
        "*.emergencyContact.*",
        "contact.message",
        "contactMessage.message",
        "EMAIL_PASSWORD",
        "emailPassword",
        "*.EMAIL_PASSWORD",
        "*.emailPassword",
      ],
    },
  };
}
